Add CI test result check

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -6,7 +6,7 @@ on:
   workflow_dispatch:
 
 jobs:
-  build:
+  test:
     strategy:
       fail-fast: false
       matrix:
@@ -97,3 +97,19 @@ jobs:
 
       - name: Test
         run: make test
+
+  result:
+    name: Test result
+    runs-on: ubuntu-latest
+    needs: [test]
+    if: ${{ always() }}
+    steps:
+      - name: Fail if any test failed
+        run: |
+          echo "Test result: ${{ needs.test.result }}"
+          if [ "${{ needs.test.result }}" != "success" ]; then
+            echo "One or more tests failed."
+            exit 1
+          fi
+      - name: All tests passed
+        run: echo "All good."
